name: album_viewer_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  web: ^1.1.1
  dawn_ui_flutter:
    git:
      url: https://github.com/itevie/dawn_ui_flutter.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
